jualmerch/urls.py
from django.urls import path
from .views import *

app_name = "jualmerch"

urlpatterns = [
    path('', landing),
    path('landing', landing, name='landing'),
    path('merchForm', merchForm, name='merchForm')
]

koncokonser/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('jualtiket/', include('jualtiket.urls')),
	path('jualmerch/', include('jualmerch.urls')),
	path('konser/', include('konser.urls')),
    path('findKonco/', include('findKonco.urls')),
]

konser/urls.py
from django.urls import path
from . import views

app_name = 'konser'

urlpatterns = [
    path('mykonser', views.konser, name='mykonser'),
    path('formkonser/', views.formkonser, name='myformkonser'),
]

jualmerch/models.py
from django.db import models

# Create your models here.


class Merch(models.Model):
    merchName = models.CharField(max_length=100)
    merchCategory = models.CharField(max_length=100)
    merchPrice = models.IntegerField(default=0)
    merchImage = models.CharField(max_length = 500)
    merchDescription = models.CharField(max_length = 500)
    concertName = models.CharField(max_length=500)

    def __str__(self):
        return self.merchName

    def price(self):
        return "Rp. " + "%.2f" %(self.merchPrice)
    

jualmerch/forms.py
from django import forms

from .models import Merch


class MerchForm(forms.Form):
    merchNameForm = forms.CharField(label = "name")
    merchCategoryForm = forms.CharField(label = "category")
    merchPriceForm = forms.IntegerField(label = "price")
    merchImageForm = forms.CharField(label = "imageUrl")
    merchDescriptionForm = forms.CharField(label = "description")
    concertNameForm = forms.CharField(label = "concert name")
    

    

jualmerch/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.http import HttpResponse

from .forms import MerchForm
from .models import Merch

# Create your views here.

def landing(request):
    concertData = Merch.objects.all()
    
    context ={
        'CONTENT': concertData
    }

    return render(request, "JualMerch.html", context)


def merchForm(request):
    form = MerchForm()

    if request.method == "POST":
        form = MerchForm(request.POST)
        print(form.errors)
        if form.is_valid():
            
            Merch.objects.create(
                merchCategory = request.POST["merchCategoryForm"],
                merchName = request.POST["merchNameForm"],
                merchPrice = request.POST["merchPriceForm"],
                merchImage = request.POST["merchImageForm"],
                merchDescription= request.POST["merchDescriptionForm"],
                concertName = request.POST["concertNameForm"]
            )


            return HttpResponseRedirect("landing")
    context = {
        'form': form
    }
    
    return render(request, "MerchForm.html", context)

jualmerch/templates/JualMerch.html
{% extends 'base.html' %}
{%load static%}
{% block title %} Merchandise {% endblock %}

{% block page_content %}
<div class = "paddingtop50" style="padding-top:50px;">
<div class="container">
    <h1 class = "h-fk">Buy Merchandise Here!</h1>
    <p class="text-fk">Kamu bisa melihat merchandise apa saja yang dijual oleh event-event konser yang akan datang</p>
</div>
<div class="container">
    {% for merch in CONTENT%}
    
        
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{{merch.merchImage}}" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title">{{merch.merchName}}</h5>
              <p class="card-text">{{merch.merchDescription}}</p>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">Price: {{merch.merchPrice}}</li>
              <li class="list-group-item">Category: {{merch.merchCategory}} </li>
              <li class="list-group-item">Related Concert: {{merch.concertName}} </li>
            </ul>
            <div class="card-body">
              <a href="{{merch.merchImage}}" class="card-link">Full Image</a>
            </div>
          </div>
        
        
    </div>
    {% endfor %}
    <div class = "container">
            <a href="{% url 'jualmerch:merchForm' %}"><button  id="bt-fk">Add Merch!</button></a>
    </div>
   
</div>
</div>
{% endblock %}

jualmerch/templates/MerchForm.html
{% extends "base.html" %}

{% load static %}
{% block page_content %}
<div class ="outer-form form-column col-4" style="padding-top:50px;" >
  <form action="" method="POST" class="all-form">
      {% csrf_token %}
    <div class="form-group ">
        <label>Merchandise Name</label>
        {{ form.merchNameForm}}
    </div>
    <div class="form-group">
       <label>Category</label>
       {{ form.merchCategoryForm}}
      
    </div>
    <div class="form-group">
       <label>Price</label>
        {{ form.merchPriceForm}}
      
    </div>
    <div class="form-group">
       <label>Desciprtion</label>
        {{ form.merchDescriptionForm }}
      
    </div>
    
    <div class="form-group">
      <label>Image url</label>
         {{ form.merchImageForm }}
    </div>
    <div class="form-group">
        <label>Related Concert</label>
        {{ form.concertNameForm}}
    </div>

    <a href="{% url 'jualmerch:landing' %}"> <button type="button" class="btn btn-primary" id="back">Back</button> </a>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock %}