findKonco/urls.py
from django.urls import path
from . import views

app_name = 'findKonco'

urlpatterns = [
    path('myfindkonco', views.findKonco, name='myfindkonco'),
    path('myformkonco/', views.formFindKonco, name='myformkonco'),
    path('mydelkonco/<id>/', views.delete_konco, name='mydelkonco'),
]

homepage/urls.py
from django.urls import path

from .views import*

app_name = "homepage"

urlpatterns = [
    path('', Homepage.as_view(), name='Homepage'),
]

jualmerch/urls.py
from django.urls import path
from .views import *

app_name = "jualmerch"

urlpatterns = [
    path('', landing),
    path('landing', landing, name='landing'),
    path('merchForm', merchForm, name='merchForm')
]

jualtiket/urls.py
from django.urls import path,include

from . import views

app_name = 'jualtiket'

urlpatterns = [
   path('viewjualtiket/', views.viewjualtiket, name='viewjualtiket'),
   path('isijualtiket/', views.isijualtiket, name='isijualtiket'),
]

koncokonser/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('jualtiket/', include('jualtiket.urls')),
	path('jualmerch/', include('jualmerch.urls')),
	path('konser/', include('konser.urls')),
    path('findKonco/', include('findKonco.urls')),
]

konser/urls.py
from django.urls import path
from . import views

app_name = 'konser'

urlpatterns = [
    path('mykonser', views.konser, name='mykonser'),
    path('formkonser/', views.formkonser, name='myformkonser'),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.views.generic import TemplateView

# Create your views here.
class Homepage(TemplateView):
    template_name = 'homepage.html'

homepage/templates/base.html
{% load static %}
<!DOCTYPE HTML>

<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'admin/css/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'admin/css/bootstrap.css' %}">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Konco Konser</title>
    </head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" >
            <a class="navbar-brand" href="{% url 'homepage:Homepage' %}">KoncoKonser</a>
            <div class= "collapse navbar-collapse" >
                <ul class="ml-auto navbar-nav">
                    <li class="nav-item"><a href="{%url 'findKonco:myfindkonco' %}">Find Your Konco Here!</a></li>
                    <li class="nav-item"><a href="{%url 'konser:mykonser'%}">Events</a></li>
                    <li class="nav-item"><a href="{%url 'jualmerch:landing' %}">Merchandise</a></li>
                    <li class="nav-item"><a href="{% url 'jualtiket:viewjualtiket' %}">Tickets</a></li>
                </ul>
            </div>
        </nav>
    </header>
    {% block page_content %}
    {% endblock %}

    <footer>
        <div class ="footer-border"  >
            <p class="text-footer"> Made with love from Arkan, Michelle, Rofi, Tesa </p>
        </div>
    </footer>
</body>
</html>

homepage/templates/homepage.html
{% extends "base.html" %}

{% load static %}
{% block page_content %}
<div class="top-lp">
    <p class="text-lp">MALAS NONTON KONSER SENDIRIAN?</p>
    <a href=#><button class="bt-lp">Find Your Konco Here!</button></a>
</div>
<div class="about-lp">
    <p class="heading-about-lp">ABOUT US</p>
    <p class="text-about-lp"> Kami adalah platform untuk menyatukan pecinta musik dari berbagai golongan dan genre</p>
</div>
{% endblock %}