jualtiket/urls.py
from django.urls import path,include

from . import views

app_name = 'jualtiket'

urlpatterns = [
   path('viewjualtiket/', views.viewjualtiket, name='viewjualtiket'),
   path('isijualtiket/', views.isijualtiket, name='isijualtiket'),
]

koncokonser/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('jualtiket/', include('jualtiket.urls')),
	path('jualmerch/', include('jualmerch.urls')),
	path('konser/', include('konser.urls')),
    path('findKonco/', include('findKonco.urls')),
]

konser/urls.py
from django.urls import path
from . import views

app_name = 'konser'

urlpatterns = [
    path('mykonser', views.konser, name='mykonser'),
    path('formkonser/', views.formkonser, name='myformkonser'),
]

jualtiket/models.py
from django.db import models

# Create your models here.
class Tiket(models.Model):
    namaKonser = models.CharField(max_length=100)
    jenisTiket = models.CharField(max_length=100)
    tempat = models.CharField(max_length=100)
    tanggal = models.DateField()
    namaPenjual = models.CharField(max_length=100)
    nomorTelepon = models.CharField(max_length=100)
    fotoTiket = models.CharField(max_length=255)
    alasan = models.CharField(max_length=255)


    def __str__(self):
        return "{}.{}".format(self.id,self.namaKonser,self.namaPenjual)

jualtiket/forms.py
from django import forms

from .models import Tiket

class tiketForm(forms.ModelForm):

    namaKonser = forms.CharField(
    widget= forms.TextInput(
        attrs= {
            "class" : "txt-form form-control",
            "required"  : True,
            "placeholder"   : "Nama Konser",
            }
        )
    )

    jenisTiket = forms.CharField(
    widget= forms.TextInput(
        attrs= {
            "class" : "txt-form form-control",
            "required"  : True,
            "placeholder"   : "Kategori",
            }
        )
    )

    tempat = forms.CharField(
    widget= forms.TextInput(
        attrs= {
            "class" : "txt-form form-control",
            "required"  : True,
            "placeholder"   : "Tempat Konser",
            }
        )
    )

    tanggal = forms.DateField(
    widget = forms.SelectDateWidget(
        attrs = {
            "class" : "pilih-tanggal form-control ",
            "required"  : True,
            }
        )
    )

    namaPenjual = forms.CharField(
    widget= forms.TextInput(
        attrs= {
            "class" : "txt-form form-control",
            "required"  : True,
            "placeholder"   : "Nama Penjual",
            }
        )
    )

    nomorTelepon = forms.CharField(
    widget= forms.TextInput(
        attrs= {
            "class" : "txt-form form-control",
            "required"  : True,
            "placeholder"   : "Nomor Telepon",
            }
        )
    )

    fotoTiket = forms.CharField(
    widget= forms.TextInput(
        attrs= {
            "class" : "txt-form form-control",
            "required"  : True,
            "placeholder"   : "Insert Your URL",
            }
        )
    )

    alasan = forms.CharField(
    widget= forms.TextInput(
        attrs= {
            "class" : "txt-form form-control",
            "required"  : True,
            "placeholder"   : "Alasan",
            }
        )
    )

    class Meta:
        model = Tiket
        fields = {
            'namaKonser',
            'jenisTiket',
            'tempat',
            'tanggal',
            'namaPenjual',
            'nomorTelepon',
            'fotoTiket',
            'alasan',
        }

jualtiket/views.py
from django.shortcuts import render,redirect

# Create your views here.
from .models import Tiket
from .forms import tiketForm

def viewjualtiket(request):
    return render(request, 'JualTiket.html')

def isijualtiket(request):
    form_jualtiket = tiketForm()

    if request.method == 'POST':
        form_jualtiket = tiketForm(request.POST)
        print(form_jualtiket.errors)
        if form_jualtiket.is_valid():
            form_jualtiket.save()
            return redirect('jualtiket:viewjualtiket')

    context = {
        'form_jualtiket':form_jualtiket,
    }

    return render(request, 'IsiJualTiket.html', {'form_jualtiket':form_jualtiket})

def viewjualtiket(request):
    list_jualtiket = Tiket.objects.all()

    context = {
        'list_jualtiket':list_jualtiket,
    }
    return render(request, 'JualTiket.html',context)

jualtiket/templates/BaseTiket.html
{% load static %}
<!DOCTYPE HTML>

<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'admin/css/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'admin/css/bootstrap.css' %}">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Konco Konser</title>
    </head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" >
            <a class="navbar-brand" href="#">KoncoKonser</a>
            <div class= "collapse navbar-collapse" >
                <ul class="ml-auto navbar-nav">
                    <li class="nav-item"><a href=#>Find Your Konco Here!</a></li>
                    <li class="nav-item"><a href=#>Events</a></li>
                    <li class="nav-item"><a href=#>Merchandise</a></li>
                    <li class="nav-item"><a href="{% url 'JualTiket' %}">Tickets</a></li>
                </ul>
            </div>
        </nav>
    </header>
    {% block page_content %}
    {% endblock %}

    <footer>
        <div class ="footer-border" >
            <p class="text-footer"> Made with love from Arkan, Michelle, Rofi, Tesa </p>
        </div>
    </footer>
</body>
</html>

jualtiket/templates/IsiJualTiket.html
{% extends "base.html" %}

{% load static %}
{% block page_content %}
<div class="tiket-lp" id="text-sell" style="padding-top:50px;">
    <p class="tiket-title-lp">Sell Your Ticket Here!</p>
    <p class="tiket-subtitle-lp">Silahkan lengkapi form berikut ini</p>
</div>
<div class ="outer-form form-column col-4 ">
  <form action="" method="POST" class="all-form">
      {% csrf_token %}

    <div class="form-group">
        <label>Nama Konser</label>
        {{ form_jualtiket.namaKonser}}
    </div>

    <div class="form-group">
       <label>Kategori</label>
       {{ form_jualtiket.jenisTiket }}
    </div>

    <div class="form-group">
       <label>Tempat Konser</label>
        {{ form_jualtiket.tempat }}
    </div>

    <label for="InputTempat">Tanggal Konser</label>
    <div class="form-row">
      <div class="col-3.5">
          {{ form_jualtiket.tanggal }}
      </div>
    </div>

    <div class="form-group ">
        <label>Nama Penjual</label>
        {{ form_jualtiket.namaPenjual}}
    </div>

    <div class="form-group">
       <label>No Telepon</label>
       {{ form_jualtiket.nomorTelepon }}
    </div>

    <div class="form-group">
       <label>Foto Tiket</label>
       {{ form_jualtiket.fotoTiket }}
    </div>

    <div class="form-group">
      <label>Alasan</label>
         {{ form_jualtiket.alasan }}
    </div>

    <a href="{% url 'jualtiket:viewjualtiket' %}"> <button type="button" class="btn btn-primary" id="back">Back</button> </a>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock %}

jualtiket/templates/JualTiket.html
{% extends "base.html" %}

{% load static %}
{% block title %} Jual Tiket {% endblock %}
{% block page_content %}

<div class="tiket-lp" style="padding-top:50px;">
    <p class="tiket-title-lp">Find Your Ticket Here!</p>
    <p class="tiket-subtitle-lp">Kamu bisa menjual tiket kamu disini jika kamu tidak bisa hadir saat hari H konser karena urusan mendadak</p>
    <a href="{% url 'jualtiket:isijualtiket' %}"><button class="bt-tiket-lp">Sell Here!</button></a>
</div>

{% for item in list_jualtiket %}
<div class="card mb-3" style="max-width: 1080px;">
  <div class="row no-gutters">
    <div class="col-md-4 gambar-tiket">
      <img src="{{ item.fotoTiket }}" class="card-img">
    </div>
    <div class="col-md-8 tiket">
      <div class="card-body">
        <h5 class="card-title">{{ item.namaKonser }}</h5>
        <h6 class="card-text">{{ item.jenisTiket }}</h6>
        <h7 class="card-text">{{ item.tempat }}, {{item.tanggal}}</h7>
        <p></p>
        <h8 class="card-text">{{ item.namaPenjual }} ({{ item.nomorTelepon }})</h8>
        <p></p>
        <p class="card-text">{{ item.alasan }}</p>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock %}